### ISSUE TITLE
Link shinyapps.io

### ISSUE THREAD

**Issue by aephidayatuloh** [melyamelia/shinycatatankeuangan#1]
Boleh ditambahkan link shinyapps.io dari aplikasi ini agar saya bisa akses secara online?

Terima kasih dan salam,
Aep

**Comment by melyamelia** [comment]
Sudah saya tambahkan pak untuk link shinyapps.io, namun untuk aplikasinya masih sama dengan versi yang dipresentasikan Hari Jumat lalu belum ada yang ditambahkan lagi.
